version: 2.1

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_material_kit_react
      - deploy:
          requires:
            - build_material_kit_react
          filters:
            branches:
              only: master

jobs:
  build_material_kit_react:
    working_directory: material-kit-react/
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build App into Docker
          command: docker build -t stevenzeiler/material-kit-react:$CIRCLE_BRANCH .
      - add_ssh_keys
      - run:
          name: Deploy to webserver
          command: |
            docker login --username $DOCKER_USER --password $DOCKER_PASSWORD
            docker push stevenzeiler/material-kit-react:$CIRCLE_BRANCH
  deploy:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - run:
          name: Update Live Container
          command: ssh ubuntu@stevenzeiler.com "sudo chef-client -o recipe[stevenzeiler.com::material-kit-react"

